<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>my_robot_co2map</name>
  <version>0.1.0</version>
  <description>
    UploadTrajectory service, RViz preview, Nav2 goal dispatch, ENS160 sampling, and CSV stats for heatmap analysis.
  </description>
  <maintainer email="vvalleay94@alumnes.ub.edu">Valeria Vallebueno Ayzikova</maintainer>
  <license>Apache-2.0</license>

  <!-- Runtime dependencies (you import these in Python nodes) -->
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>ens160_interfaces</exec_depend>

  <!-- If this package defines its own .srv/.msg (e.g., UploadTrajectory), keep these: -->
  <build_depend>rosidl_default_generators</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>

  <!-- Test dependencies (optional) -->
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <!-- Build type -->
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
